
default: &default
  adapter: postgresql
  encoding: utf8
  username: pguser
  host: localhost
  port: 5432
  pool: 5
  password: '123'

development:
  <<: *default
  database: rich-active-admin-test-app-development